version: '3.9'

services:

  primary:
    image: mysql/mysql-server:8.0
    container_name: primary
    hostname: primary
    ports:
      - '3306:3306'
    restart: unless-stopped
    command: [ "mysqld", "--loose-group-replication-local-address=primary:6606" ]
    env_file: .env
    volumes:
      - primary_volume:/var/lib/mysql
      - ./conf.d/my.cnf:/etc/mysql/my.cnf
      - ./initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 2s
      retries: 20

  replica_1:
    image: mysql/mysql-server:8.0
    container_name: replica_1
    hostname: replica_1
    ports:
      - '3307:3306'
    restart: unless-stopped
    command: [ "mysqld", "--loose-group-replication-local-address=replica_1:6606" ]
    env_file: .env
    volumes:
      - replica_1_volume:/var/lib/mysql
      - ./conf.d/my.cnf:/etc/mysql/my.cnf
      - ./initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 2s
      retries: 20

  replica_2:
    image: mysql/mysql-server:8.0
    container_name: replica_2
    hostname: replica_2
    ports:
      - '3308:3306'
    restart: unless-stopped
    command: [ "mysqld", "--loose-group-replication-local-address=replica_2:6606" ]
    env_file: .env
    volumes:
      - replica_2_volume:/var/lib/mysql
      - ./conf.d/my.cnf:/etc/mysql/my.cnf
      - ./initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 2s
      retries: 20

volumes:
  primary_volume: { }
  replica_1_volume: { }
  replica_2_volume: { }
